# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ceb53410d2fd27a5a807abebba5a6e39dda5f6bacebc122fb597059fc8b8e64962f6b3b3037d9dbb65befc1a0bdbb1ab1f81ade4e75be40713055a5e7f08457

test:
  secret_key_base: ae2e824f20a9953735c0c240b7889e0b427a13badeb52c16c79128f9213794445c890d7b9629ff1f93bbdef81c49c034272dda2875fc08ec6596d3617c455034

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
